// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1, arg2) {
  return window['go']['main']['App']['CloseTerminal'](arg1, arg2);
}

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3);
}

export function CreateTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2, arg3);
}

export function DetectShells() {
  return window['go']['main']['App']['DetectShells']();
}

export function FinishTask(arg1) {
  return window['go']['main']['App']['FinishTask'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HasRunningTasks() {
  return window['go']['main']['App']['HasRunningTasks']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function OpenTaskFolder(arg1) {
  return window['go']['main']['App']['OpenTaskFolder'](arg1);
}

export function PrepareQuit() {
  return window['go']['main']['App']['PrepareQuit']();
}

export function ResizeTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3, arg4);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}

export function WriteTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2, arg3);
}
