// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSelectedTerminal() {
  return window['go']['main']['App']['ClearSelectedTerminal']();
}

export function CloseTerminal(arg1, arg2) {
  return window['go']['main']['App']['CloseTerminal'](arg1, arg2);
}

export function CopyLifecycleCommandChain(arg1) {
  return window['go']['main']['App']['CopyLifecycleCommandChain'](arg1);
}

export function CreateCommandTerminal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateCommandTerminal'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3);
}

export function CreateTaskWithExtraInfo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTaskWithExtraInfo'](arg1, arg2, arg3, arg4);
}

export function CreateTaskWithExtraInfoAndLifecycleChains(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateTaskWithExtraInfoAndLifecycleChains'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTaskWithExtraInfoAndTemplateFields(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateTaskWithExtraInfoAndTemplateFields'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTaskWithExtraInfoTemplateFieldsAndLifecycleChains(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateTaskWithExtraInfoTemplateFieldsAndLifecycleChains'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2, arg3);
}

export function DeleteExtraInfo(arg1) {
  return window['go']['main']['App']['DeleteExtraInfo'](arg1);
}

export function DeleteExtraInfoCatalogue(arg1) {
  return window['go']['main']['App']['DeleteExtraInfoCatalogue'](arg1);
}

export function DeleteExtraInfoTemplate(arg1) {
  return window['go']['main']['App']['DeleteExtraInfoTemplate'](arg1);
}

export function DeleteLifecycleCommand(arg1) {
  return window['go']['main']['App']['DeleteLifecycleCommand'](arg1);
}

export function DeleteLifecycleCommandChain(arg1) {
  return window['go']['main']['App']['DeleteLifecycleCommandChain'](arg1);
}

export function DetectShells() {
  return window['go']['main']['App']['DetectShells']();
}

export function ExecuteTaskMenuCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteTaskMenuCommand'](arg1, arg2, arg3, arg4);
}

export function FinishTask(arg1) {
  return window['go']['main']['App']['FinishTask'](arg1);
}

export function GetLifecycleCommandInput(arg1) {
  return window['go']['main']['App']['GetLifecycleCommandInput'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HasRunningTasks() {
  return window['go']['main']['App']['HasRunningTasks']();
}

export function ListExtraInfoCatalogues() {
  return window['go']['main']['App']['ListExtraInfoCatalogues']();
}

export function ListExtraInfoTemplates() {
  return window['go']['main']['App']['ListExtraInfoTemplates']();
}

export function ListExtraInfos() {
  return window['go']['main']['App']['ListExtraInfos']();
}

export function ListLifecycleCommandChains() {
  return window['go']['main']['App']['ListLifecycleCommandChains']();
}

export function ListLifecycleCommands() {
  return window['go']['main']['App']['ListLifecycleCommands']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function OpenTaskFolder(arg1) {
  return window['go']['main']['App']['OpenTaskFolder'](arg1);
}

export function PrepareQuit() {
  return window['go']['main']['App']['PrepareQuit']();
}

export function ReorderTasks(arg1, arg2) {
  return window['go']['main']['App']['ReorderTasks'](arg1, arg2);
}

export function ReportTerminalTitleActivity(arg1, arg2) {
  return window['go']['main']['App']['ReportTerminalTitleActivity'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3, arg4);
}

export function RetryTaskLifecycleCommandChain(arg1) {
  return window['go']['main']['App']['RetryTaskLifecycleCommandChain'](arg1);
}

export function RunTaskCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunTaskCommand'](arg1, arg2, arg3);
}

export function SaveExtraInfo(arg1) {
  return window['go']['main']['App']['SaveExtraInfo'](arg1);
}

export function SaveExtraInfoCatalogue(arg1) {
  return window['go']['main']['App']['SaveExtraInfoCatalogue'](arg1);
}

export function SaveExtraInfoTemplate(arg1) {
  return window['go']['main']['App']['SaveExtraInfoTemplate'](arg1);
}

export function SaveLifecycleCommand(arg1) {
  return window['go']['main']['App']['SaveLifecycleCommand'](arg1);
}

export function SaveLifecycleCommandChain(arg1) {
  return window['go']['main']['App']['SaveLifecycleCommandChain'](arg1);
}

export function SaveLifecycleDefaultChain(arg1, arg2) {
  return window['go']['main']['App']['SaveLifecycleDefaultChain'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectTerminal(arg1, arg2) {
  return window['go']['main']['App']['SelectTerminal'](arg1, arg2);
}

export function SetTaskShelved(arg1, arg2) {
  return window['go']['main']['App']['SetTaskShelved'](arg1, arg2);
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}

export function UpdateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3, arg4);
}

export function UpdateTaskWithExtraInfo(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateTaskWithExtraInfo'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateTaskWithExtraInfoAndLifecycleChains(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateTaskWithExtraInfoAndLifecycleChains'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateTaskWithExtraInfoAndTemplateFields(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateTaskWithExtraInfoAndTemplateFields'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateTaskWithExtraInfoTemplateFieldsAndLifecycleChains(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateTaskWithExtraInfoTemplateFieldsAndLifecycleChains'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function WriteTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2, arg3);
}
