// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {terminal} from '../models';
import {task} from '../models';
import {application} from '../models';
import {quickinput} from '../models';

export function ClearSelectedTerminal():Promise<void>;

export function CloseTerminal(arg1:string,arg2:string):Promise<void>;

export function CopyLifecycleCommandChain(arg1:string):Promise<settings.LifecycleCommandChain>;

export function CopyLifecyclePreset(arg1:string):Promise<settings.LifecyclePreset>;

export function CreateCommandTerminal(arg1:string,arg2:string,arg3:Array<string>,arg4:number,arg5:number):Promise<terminal.Info>;

export function CreateTask(arg1:string,arg2:string,arg3:string):Promise<task.Task>;

export function CreateTaskWithExtraInfo(arg1:string,arg2:string,arg3:string,arg4:Array<task.TaskExtraInfo>):Promise<task.Task>;

export function CreateTaskWithExtraInfoAndLifecycleChains(arg1:string,arg2:string,arg3:string,arg4:Array<task.TaskExtraInfo>,arg5:Record<task.LifecycleHook, string>):Promise<task.Task>;

export function CreateTaskWithExtraInfoAndTemplateFields(arg1:string,arg2:string,arg3:string,arg4:Array<task.TaskExtraInfo>,arg5:Record<string, any>):Promise<task.Task>;

export function CreateTaskWithExtraInfoTemplateFieldsAndLifecycleChains(arg1:string,arg2:string,arg3:string,arg4:Array<task.TaskExtraInfo>,arg5:Record<string, any>,arg6:Record<task.LifecycleHook, string>):Promise<task.Task>;

export function CreateTerminal(arg1:string,arg2:number,arg3:number):Promise<terminal.Info>;

export function DeleteCompletedTasks(arg1:Array<string>):Promise<Array<task.Task>>;

export function DeleteExtraInfo(arg1:string):Promise<void>;

export function DeleteExtraInfoCatalogue(arg1:string):Promise<void>;

export function DeleteExtraInfoTemplate(arg1:string):Promise<void>;

export function DeleteLifecycleCommand(arg1:string):Promise<void>;

export function DeleteLifecycleCommandChain(arg1:string):Promise<void>;

export function DeleteLifecyclePreset(arg1:string):Promise<void>;

export function DeleteQuickInput(arg1:string):Promise<void>;

export function DetectShells():Promise<Array<string>>;

export function ExecuteTaskMenuCommand(arg1:string,arg2:string,arg3:number,arg4:number):Promise<application.TaskMenuCommandResult>;

export function FinishTask(arg1:string):Promise<task.Task>;

export function GetLifecycleCommandInput(arg1:string):Promise<string>;

export function GetSettings():Promise<settings.Settings>;

export function HasRunningTasks():Promise<boolean>;

export function ListExtraInfoCatalogues():Promise<Array<string>>;

export function ListExtraInfoTemplates():Promise<Array<task.ExtraInfoTemplate>>;

export function ListExtraInfos():Promise<Array<task.ExtraInfo>>;

export function ListLifecycleCommandChains():Promise<Array<settings.LifecycleCommandChain>>;

export function ListLifecycleCommands():Promise<Array<settings.LifecycleCommand>>;

export function ListLifecyclePresets():Promise<Array<settings.LifecyclePreset>>;

export function ListQuickInputs():Promise<Array<quickinput.QuickInput>>;

export function ListTasks():Promise<Array<task.Task>>;

export function OpenTaskFolder(arg1:string):Promise<void>;

export function PrepareQuit():Promise<void>;

export function ReorderQuickInputs(arg1:Array<string>):Promise<Array<quickinput.QuickInput>>;

export function ReorderTasks(arg1:task.Status,arg2:Array<string>):Promise<Array<task.Task>>;

export function ReportTerminalTitleActivity(arg1:string,arg2:string):Promise<boolean>;

export function ResizeTerminal(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function RetryTaskLifecycleCommandChain(arg1:string):Promise<task.Task>;

export function RunTaskCommand(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SaveDefaultLifecyclePreset(arg1:string):Promise<settings.Settings>;

export function SaveExtraInfo(arg1:task.ExtraInfo):Promise<task.ExtraInfo>;

export function SaveExtraInfoCatalogue(arg1:string):Promise<string>;

export function SaveExtraInfoTemplate(arg1:task.ExtraInfoTemplate):Promise<task.ExtraInfoTemplate>;

export function SaveLifecycleCommand(arg1:settings.LifecycleCommand):Promise<settings.LifecycleCommand>;

export function SaveLifecycleCommandChain(arg1:settings.LifecycleCommandChain):Promise<settings.LifecycleCommandChain>;

export function SaveLifecyclePreset(arg1:settings.LifecyclePreset):Promise<settings.LifecyclePreset>;

export function SaveQuickInput(arg1:quickinput.QuickInput):Promise<quickinput.QuickInput>;

export function SaveSettings(arg1:settings.Settings):Promise<settings.Settings>;

export function SelectTerminal(arg1:string,arg2:string):Promise<void>;

export function SetTaskShelved(arg1:string,arg2:boolean):Promise<Array<task.Task>>;

export function StartTask(arg1:string):Promise<task.Task>;

export function UpdateTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<task.Task>;

export function UpdateTaskWithExtraInfo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<task.TaskExtraInfo>):Promise<task.Task>;

export function UpdateTaskWithExtraInfoAndLifecycleChains(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<task.TaskExtraInfo>,arg6:Record<task.LifecycleHook, string>):Promise<task.Task>;

export function UpdateTaskWithExtraInfoAndTemplateFields(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<task.TaskExtraInfo>,arg6:Record<string, any>):Promise<task.Task>;

export function UpdateTaskWithExtraInfoTemplateFieldsAndLifecycleChains(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<task.TaskExtraInfo>,arg6:Record<string, any>,arg7:Record<task.LifecycleHook, string>):Promise<task.Task>;

export function WriteTerminal(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteTerminalFilePaths(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;
