// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {terminal} from '../models';
import {task} from '../models';
import {settings} from '../models';

export function CloseTerminal(arg1:string,arg2:string):Promise<void>;

export function CreateCommandTerminal(arg1:string,arg2:string,arg3:Array<string>,arg4:number,arg5:number):Promise<terminal.Info>;

export function CreateTask(arg1:string,arg2:string,arg3:string):Promise<task.Task>;

export function CreateTerminal(arg1:string,arg2:number,arg3:number):Promise<terminal.Info>;

export function DetectShells():Promise<Array<string>>;

export function FinishTask(arg1:string):Promise<task.Task>;

export function GetSettings():Promise<settings.Settings>;

export function HasRunningTasks():Promise<boolean>;

export function ListTasks():Promise<Array<task.Task>>;

export function OpenTaskFolder(arg1:string):Promise<void>;

export function PrepareQuit():Promise<void>;

export function ResizeTerminal(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function RunTaskCommand(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<settings.Settings>;

export function StartTask(arg1:string):Promise<task.Task>;

export function UpdateTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<task.Task>;

export function WriteTerminal(arg1:string,arg2:string,arg3:string):Promise<void>;
